### ISSUE TITLE
Tell them to code-a-long at the top

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/js-principles-errors-and-stack-traces-readme#1]
You never tell them to codealong at the top, but then expect it at the bottom

**Comment by gj** [comment]
There are pretty explicit instructions to start coding along halfway through:
>Open up `index.html` in your browser.

>***NOTE***: If you're in the IDE, follow [these steps](http://help.learn.co/the-learn-ide/common-ide-questions/viewing-html-pages-in-the-learn-ide). For local environments, there are a ton of different ways to do this. It will vary based on your operating system, but double clicking on the file in your file system should work on every OS. On macOS, you can type `open index.html` in the lesson's directory in your terminal. On Linux, the equivalent command is likely `xdg-open index.html`, and on Windows it should be `start index.html`.

>When the file's open in your browser, open the JS console, and you should see something similar to the following error:

and so on
