### ISSUE TITLE
Do they know about nested functions? Lets' just have two regular functions that call each other

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/js-principles-errors-and-stack-traces-readme#3]
```
function first () {
  function second () {
    const third = 'Declaring a new variable.';

    third();
  }

  second();
}

first();
```

Why not just have regular functions instead of the nesting stuff and have them call each other?

**Comment by gj** [comment]
Fixed in https://github.com/learn-co-curriculum/js-principles-errors-and-stack-traces-readme/commit/ff12458ecda2e8e5c67ae9e0ffcc5dad7b8890f5
