### ISSUE TITLE
Scope Lab Irony

### ISSUE THREAD

**Issue by skmcloughlin** [learn-co-curriculum/js-principles-errors-and-stack-traces-readme#4]
Just an FYI, the Scope Lab in the principles section of the new Javascript curriculum the last two tests ask us to create errors that aren't discussed until two lessons later in the "Errors and Stack Traces" lesson. After some Googling, I was able to pass the lab by just writing:

```
function changeLeastFavoriteCustomer() {
  throw new TypeError
}

function attemptTwoFavoriteCustomers(input) {
  throw new SyntaxError
}
```

I believe I now see what the tests were expecting me to do.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @skmcloughlin.

We have noted this issue and will be resolving it in an upcoming version update to our content. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
