### ISSUE TITLE
Instructions to access index.html do not exist

### ISSUE THREAD

**Issue by tracypholmes** [learn-co-curriculum/js-principles-errors-and-stack-traces-readme#6]
This is pushed as a lesson in the curriculum, not a lab or codealong. The README asks us to 'open index.html'. However, there are no instructions to clone or fork the repo. Screenshot provided

![image](https://user-images.githubusercontent.com/12778804/33293203-9ea2d946-d391-11e7-9371-731aee177c93.png)

**Comment by cjbrock** [comment]
Bug fixed by commit above! 

// <3 Corinna
