### ISSUE TITLE
More explicit instructions for Local 

### ISSUE THREAD

**Issue by Sidhe-is-me** [learn-co-curriculum/js-principles-errors-and-stack-traces-readme#7]
Please be more explicit that the lesson will need to be cloned from GitHub.

![screen shot 2018-03-08 at 1 14 52 pm](https://user-images.githubusercontent.com/13264422/37168399-c905a462-22d2-11e8-91e6-0c769873a0c0.png)

**Comment by cjbrock** [comment]
Bug fixed by commit above!

// <3 Corinna
